### ISSUE TITLE
hermes harvest return 0 on error

### ISSUE THREAD

**Issue by daniel-mohr** [softwarepub/hermes#204]
Following [Set up automatic software publishing](https://docs.software-metadata.pub/en/latest/tutorials/automated-publication-with-ci.html) I created a `CITATION.cff` and in the end in the pipeline the upload to zenodo sandbox fails with `Error in 'hermes.deposit.publish' entry point 'invenio': With access_right open, a license is required.`.

The reason was that `hermes harvest` already claims:

```
!!! warning "CITATION.cff is not valid according to <https://citation-file-format.github.io/1.2.0/schema.json>"
    Invalid input for `root`.
    !!! message "'message' is a required property"
```

But still the command returned 0 and the pipeline passed. And for a user no error is  recognizable.

I would suggest that `hermes` return an other value than 0 on error. Then the pipeline would break and the user is pointed to the error.

**Comment by daniel-mohr** [comment]
I do not think that a harvesters should be allowed to fail. If the harvester if configured it should work. Otherwise a user can decide to use only some, e. g.:

```
[harvest]
from = [ "git" ]
```

**Comment by daniel-mohr** [comment]
Maybe it could also be interesting to provide the user a simple solution to check the cff file, e. g. as gitlab ci pipeline using [cffconvert](https://github.com/citation-file-format/cffconvert) and an official docker image (The provided [citationcff/cffconvert](https://hub.docker.com/r/citationcff/cffconvert) docker image is pretty old and based on an old alpine:3.14.1.):

```yaml
cffconvert__alpine:
  stage: pre
  image:
    name: alpine:latest
  script:
    - date
    - cat /etc/os-release
    - apk add --no-cache py3-attrs py3-click py3-dateutil py3-docopt py3-jsonschema py3-packaging py3-parsing py3-pip py3-pykwalify py3-pyrsistent py3-requests py3-retrying py3-setuptools py3-six
    - pip3 install cffconvert
    - cffconvert --validate
```

Or using the [pre-commit hook](https://github.com/citation-file-format/cffconvert#pre-commit-hook).

This could be mentioned in the documentation.
