### ISSUE TITLE
Add Rodare option to hermes init

### ISSUE THREAD

**Issue by zyzzyxdonta** [softwarepub/hermes#345]
In `hermes init` it should be possible to select Rodare as the target for the deposit step.

The plugin is implemented here: https://github.com/softwarepub/hermes/blob/develop/src/hermes/commands/deposit/rodare.py

I would suggest showing "Rodare (for HZDR employees)" as an option for the deposit platform. If Rodare is selected, users should be shown the following text (or something similar):

>In order to publish your software on Rodare, you first need to register it in Robis (https://www.hzdr.de/robis). Only enter the general metadata, but **don't** add a "publication form". Robis will assign an ID ("Publ.-Id") to your publication. Please enter this ID here.

And then they should enter this ID.

The snippet for the `hermes.toml` that should be generated looks like this (I used Publ.Id: 12345 in this example):

```toml
[deposit]
target = "rodare"

[deposit.rodare]
robis_pub_id = 12345
```

Additionally, `[deposit.rodare]` may have the following fields inherited from the Invenio plugin:

```toml
communities = ["rodare"]
access_right = "open"
```

For `access_right`, I think we should ask the user. `communities` should be pre-filled with `["rodare"]` (which is the community for things to show up on the front page.
